runtime: nodejs10
instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
  - url: /notary
    static_dir: dist/notary

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
